version: '3.6'
services:
  rsntp:
    build: .
    image: publicarray/rsntp
    command: -d chrony
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.3'
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "123:123"
